--VIEWS

-- SAO A ORGANIZAÇÃO LOGICA DE SUA CONSULTA
--FICA ARMAZENAD NO ORACLE A INSTRUCAO SQL DA SUA CONSULTA
-- E CADA VEZ QUE É EXECUTADA O ORACLE REFAZ A CONSULTA.

--MUITAS VEZES UTILIZADAS PARA ESCONDER CAMPOS DE UMA TABELA.
/* EXEMPLO ESCONDER SALARIO DE UM FUNCIONARIO:

*/

SELECT * FROM EMP;

SELECT ENAME, JOB, HIREDATE FROM EMP;
CREATE OR REPLACE VIEW V_EMP_DADOS_BASICOS AS

SELECT ENAME, JOB, HIREDATE FROM EMP;

SELECT * FROM V_EMP_DADOS_BASICOS;

CREATE OR REPLACE VIEW V_EMP_DEPT AS
SELECT EM.ENAME ,DT.DNAME FROM DEPT DT INNER JOIN EMP EM ON
(DT.DEPTNO = EM.DEPTNO);

SELECT * FROM V_EMP_DEPT;

SELECT * FROM USER_VIEWS
23

CREATE OR REPLACE VIEW V_LIVRO_LIVRARIA_LIVRO AS
SELECT
    DISTINCT
    LV.TX_TITULO,
    LL.NR_QUANT
FROM 
    T_BS_LIVRO LV
LEFT JOIN
    T_BS_LIVRO_LIVRARIA LL
ON 
    (LV.CD_CODIGO = LL.CD_CODIGO)
WHERE 
    LL.NR_QUANT IS NULL OR NR_QUANT =0
ORDER BY
    LL.NR_QUANT


SELECT * FROM V_LIVRO_LIVRARIA_LIVRO



